# Site wide configuration

title: Deep Data Solutions
description: "Doradctwo, projektowanie i implementacja rozwiazań z dziedziny inteligentnej analizy danych dla przemysłu, biznesu oraz badań naukowych."
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: //mmistakes.github.io/skinny-bones-jekyll

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Andrzej Marciniak
  web: http://deepdatasolutions.pl
  email: Andrzej.Marciniak@deepdatasolutions.pl
  twitter: 
  bio: 
  avatar: #bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]